---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinesweetshop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinesweetshop
  template:
    metadata:
      labels:
        app: onlinesweetshop
    spec:
      containers:
      - name: onlinesweetshop
        image: rithikmfj/onlinesweetshop
        ports:
        - name: http-port
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: onlinesweetshop-servicedb
spec:
  ports:
  - port: 8080
    nodePort: 32001
    targetPort: http-port
    protocol: TCP
  selector:
    app: onlinesweetshop
  type: NodePort